name: Update Lark Wiki Pages
on:
  workflow_dispatch:
    inputs:
      cache:
        description: "if use lark-pages cache"
        required: false
        default: "true"
  schedule:
    # Every 3 days at 00:00
    - cron: "0 0 */3 * *"

jobs:
  export:
    name: Download lark wiki pages
    timeout-minutes: 180
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          branch: main

      - name: Clear cache if cache is false
        if: ${{ inputs.cache == 'false' }}
        run: |
          rm -rf ./lark-pages/en/.cache/blocks
          rm -rf ./lark-pages/zh-HK/.cache/blocks

      - uses: oven-sh/setup-bun@v1

      - name: Download lark wiki pages
        env:
          FEISHU_APP_ID: ${{ secrets.LARK_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.LARK_APP_SECRET }}
          FEISHU_SPACE_ID: ${{ secrets.LARK_SPACE_ID }}
          PORTAI_API_KEY: ${{ secrets.PORTAI_API_KEY }}
          PORTAI_UID: ${{ secrets.PORTAI_UID }}
        run: |
          bun install
          bun run lark-zh-HK-export
          bun run lark-en-export
          bun run lark-setup
          bun run auto-translate-new
          bun run lark-en-export
          bun run lark-setup

      - name: Setup Git
        run: |
          git config --global user.name "Longbridge Whale docs bot"
          git config --global user.email "longbridge-whale-docs@users.noreply.github.com"

      - name: Create PR for lark-locales/ updates
        run: |
          BRANCH_NAME=lark-update-$(date +'%Y%m%d%H%M%S')
          git checkout -b $BRANCH_NAME
          git status
          git add .
          git commit -m "Commit lark updated pages to repo"
          git push origin $BRANCH_NAME

          # Create Pull Request
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"title":"Update lark wiki pages","head":"'$BRANCH_NAME'","base":"main"}' https://api.github.com/repos/${{ github.repository }}/pulls

